<?php
include_once('connection/conJSON.php');

$ID_REPORTE=$_GET['ID_REPORTE'];
$AREA_SERVICIO=$_POST['AREA_SERVICIO'];
$EQUIPO=$_POST['EQUIPO'];
$EXT=$_POST['EXT'];
$REPORTA=$_POST['REPORTA'];
$DESCRIPCION_REPORTE=$_POST['DESCRIPCION_REPORTE'];
$ASIGNADO=$_POST['ASIGNADO'];
$COMENTARIOS=$_POST['COMENTARIOS'];
$RECIBE_REPORTE=$_POST['RECIBE_REPORTE'];


$sql="UPDATE reportes SET AREA_SERVICIO='$AREA_SERVICIO', EQUIPO='$EQUIPO', EXT='$EXT', REPORTA='$REPORTA', DESCRIPCION_REPORTE='$DESCRIPCION_REPORTE',ASIGNADO='$ASIGNADO', COMENTARIOS='$COMENTARIOS', RECIBE_REPORTE= '$RECIBE_REPORTE'  WHERE ID_REPORTE='$ID_REPORTE'";

$equipo=     getArraySQL($sql);

echo json_encode($sql);
?>