<?php
include_once('connection/conJSON.php');
$ID_PROVEEDOR=$_POST['ID_PROVEEDOR'];
$PROVEEDOR=$_POST['PROVEEDOR'];
$DIRECCION=$_POST['DIRECCION'];
$CONTACTO1=$_POST['CONTACTO1'];
$TELEFONO1=$_POST['TELEFONO1'];
$EMAIL1=$_POST['EMAIL1'];

$CONTACTO2=$_POST['CONTACTO2'];
$TELEFONO2=$_POST['TELEFONO2'];
$EMAIL2=$_POST['EMAIL2'];

$CONTACTO3=$_POST['CONTACTO3'];
$TELEFONO3=$_POST['TELEFONO3'];
$EMAIL3=$_POST['EMAIL3'];

$MARCAS=$_POST['MARCAS'];
$EQUIPOS=$_POST['EQUIPOS'];
$ESTADO=$_POST['ESTADO'];
$ESTADO_REPUBLICA=$_POST['ESTADO_REPUBLICA'];


$sql_insert="UPDATE proveedores SET PROVEEDOR='$PROVEEDOR', DIRECCION='$DIRECCION', CONTACTO1='$CONTACTO1', TELEFONO1='$TELEFONO1', EMAIL1='$EMAIL1', CONTACTO2='$CONTACTO2', EMAIL2='$EMAIL2', CONTACTO3='$CONTACTO3', TELEFONO3='$TELEFONO3', EMAIL3='$EMAIL3', MARCAS='$MARCAS', EQUIPOS='$EQUIPOS', ESTADO='$ESTADO', ESTADO_REPUBLICA='$ESTADO_REPUBLICA' WHERE ID_PROVEEDOR='$ID_PROVEEDOR'";

echo $sql_insert;
$row_insert=setArraySQL($sql_insert);

 echo json_encode($row_insert);


?>