<?php
include_once('connection/conJSON.php');

$ID_EQUIPO_INVENTARIO=$_GET['idEquipo'];

//$NO_CONTROL=$_POST['NO_CONTROL'];
//$ID_EQUIPO=$_POST['ID_EQUIPO'];

$MODELO=$_POST['MODELO'];
$SERIE=$_POST['SERIE'];	
$MARCA=$_POST['MARCA'];	
$NO_INVENTARIO=$_POST['NO_INVENTARIO'];
$ID_AREA=$_POST['ID_AREA'];

$ID_PROVEEDOR=$_POST['ID_PROVEEDOR'];	

$FECHA_DE_INSTALACION=$_POST['FECHA_DE_INSTALACION'];
$ESTADO	=$_POST['ESTADO'];
$PROPIEDAD=$_POST['PROPIEDAD'];
$PRECIO=$_POST['PRECIO'];
$FECHA_CREACION=$_POST['FECHA_CREACION'];
$GARANTIA=$_POST['GARANTIA'];
$COMPRA_POR=$_POST['COMPRA_POR'];
$CONVENIO_EVENTO=$_POST['CONVENIO_EVENTO'];
$PARTIDA=$_POST['PARTIDA'];	
$NOTAS=$_POST['NOTAS'];
$FECHA_COMPRA=$_POST['FECHA_COMPRA'];
$VIDA_UTIL=$_POST['VIDA_UTIL'];
$FECHA_BAJA=$_POST['FECHA_BAJA']; 
$APARTIRDE=$_POST['APARTIRDE'];
$OBSOLESCENCIA=$_POST['OBSOLESCENCIA'];
$OBSERVACIONES=$_POST['OBSERVACIONES'];

/*$sql_equipo="SELECT * FROM catalogo_equipos WHERE ID_EQUIPO='$ID_EQUIPO'";

$row_equipo=getArraySQL($sql_equipo);
  
$EQUIPO=$row_equipo[0]['EQUIPO'];	*/


$sql_area="SELECT * FROM areasinventario WHERE ID_AREA='$ID_AREA'";

$row_area=getArraySQL($sql_area);


$AREA=$row_area[0]['SERVICIO'];
$SERVICIO=$row_area[0]['AREA'];
$CUERPO=$row_area[0]['CUERPO'];


$sql_proveedor="SELECT * FROM proveedores WHERE ID_PROVEEDOR='$ID_PROVEEDOR'";
$row_proveedor=getArraySQL($sql_proveedor);
$PROVEEDOR=$row_proveedor[0]['PROVEEDOR'];

$sql_insert="UPDATE equipoinventario SET MODELO='$MODELO', SERIE='$SERIE', MARCA='$MARCA', NO_INVENTARIO='$NO_INVENTARIO', ID_AREA='$ID_AREA', AREA='$AREA', SERVICIO='$SERVICIO', CUERPO='$CUERPO', ID_PROVEEDOR='$ID_PROVEEDOR', PROVEEDOR='$PROVEEDOR', FECHA_DE_INSTALACION='$FECHA_DE_INSTALACION', ESTADO='$ESTADO',  PRECIO='$PRECIO',APARTIRDE='$APARTIRDE' ,GARANTIA='$GARANTIA', COMPRA_POR='$COMPRA_POR', CONVENIO_EVENTO='$CONVENIO_EVENTO', PARTIDA='$PARTIDA', NOTAS='$NOTAS', FECHA_COMPRA='$FECHA_COMPRA', FECHA_BAJA='$FECHA_BAJA', OBSOLESCENCIA='$OBSOLESCENCIA',  OBSERVACIONES='$OBSERVACIONES'  WHERE ID_EQUIPO_INVENTARIO='$ID_EQUIPO_INVENTARIO'";

//echo $sql_insert;
$row_insert=setArraySQL($sql_insert);
 echo json_encode($row_insert);


?>