<?php
include_once('connection/conJSON.php');


$NO_CONTROL=$_POST['NO_CONTROL'];
$ID_EQUIPO=$_POST['ID_EQUIPO'];

$MODELO=$_POST['MODELO'];
$SERIE=$_POST['SERIE'];	
$MARCA=$_POST['MARCA'];	
$NO_INVENTARIO=$_POST['NO_INVENTARIO'];
$ID_AREA=$_POST['ID_AREA'];

$ID_PROVEEDOR=$_POST['PROVEEDOR'];	

$FECHA_DE_INSTALACION=$_POST['FECHA_DE_INSTALACION'];
$ESTADO	=$_POST['ESTADO'];
$PROPIEDAD=$_POST['PROPIEDAD'];
$PRECIO=$_POST['PRECIO'];
$FECHA_CREACION=$_POST['FECHA_CREACION'];
$GARANTIA=$_POST['GARANTIA'];
$COMPRA_POR=$_POST['COMPRA_POR'];
$CONVENIO_EVENTO=$_POST['CONVENIO_EVENTO'];
$PARTIDA=$_POST['PARTIDA'];	
$NOTAS=$_POST['NOTAS'];
$FECHA_COMPRA=$_POST['FECHA_COMPRA'];
$VIDA_UTIL=$_POST['VIDA_UTIL'];
$APARTIRDE=$_POST['APARTIRDE'];
$OBSERVACIONES=$_POST['OBSERVACIONES'];

$sql_equipo="SELECT * FROM catalogo_equipos WHERE ID_EQUIPO='$ID_EQUIPO'";

$row_equipo=getArraySQL($sql_equipo);
  
$EQUIPO=$row_equipo[0]['EQUIPO'];	


$sql_area="SELECT * FROM areasinventario WHERE ID_AREA='$ID_AREA'";

$row_area=getArraySQL($sql_area);


$AREA=$row_area[0]['SERVICIO'];
$SERVICIO=$row_area[0]['AREA'];
$CUERPO=$row_area[0]['CUERPO'];


$sql_proveedor="SELECT * FROM proveedores WHERE ID_PROVEEDOR='$ID_PROVEEDOR'";
$row_proveedor=getArraySQL($sql_proveedor);
$PROVEEDOR=$row_proveedor[0]['PROVEEDOR'];

$sql_insert="INSERT INTO equipoinventario(NO_CONTROL, ID_EQUIPO, EQUIPO, MODELO, SERIE, MARCA, NO_INVENTARIO, ID_AREA, AREA, SERVICIO, CUERPO,ID_PROVEEDOR, PROVEEDOR, FECHA_DE_INSTALACION, ESTADO, PROPIEDAD, PRECIO, FECHA_CREACION, APARTIRDE, GARANTIA, COMPRA_POR, CONVENIO_EVENTO, PARTIDA, NOTAS, FECHA_COMPRA, VIDA_UTIL, OBSERVACIONES) VALUES ('$NO_CONTROL', '$ID_EQUIPO', '$EQUIPO','$MODELO', '$SERIE', '$MARCA', '$NO_INVENTARIO', '$ID_AREA', '$AREA', '$SERVICIO', '$CUERPO','$ID_PROVEEDOR', '$PROVEEDOR', '$FECHA_DE_INSTALACION', '$ESTADO', '$PROPIEDAD', '$PRECIO', '$FECHA_CREACION','$APARTIRDE', '$GARANTIA', '$COMPRA_POR', '$CONVENIO_EVENTO', '$PARTIDA', '$NOTAS', '$FECHA_COMPRA', '$VIDA_UTIL', '$OBSERVACIONES')";

$row_insert=setArraySQL($sql_insert);

 echo json_encode($row_insert);


?>