<?php
include_once('connection/conJSON.php');


$ORDEN_SERVICIO='NA';
$REQUISICION_POR=$_POST['REQUISICION_POR'];
$EDO_REQUISICION=$_POST['EDO_REQUISICION'];
$FECHA_SOLICITUD_ALMACEN=$_POST['FECHA_SOLICITUD_ALMACEN'];
$FECHA_SUMINISTRO=$_POST['FECHA_SUMINISTRO'];
$NUM_F=$_POST['NUM_F'];
$COMENTARIOS=$_POST['COMENTARIOS'];
$REALIZO=$_POST['REALIZO'];
$OTRO_REQUISICION_POR=$_POST['OTRO_REQUISICION_POR'];

$sql_insert="INSERT INTO requisiciones (ORDEN_SERVICIO, REQUISICION_POR,OTRO_REQUISICION_POR, EDO_REQUISICION, FECHA_SOLICITUD_ALMACEN, FECHA_SUMINISTRO, NUM_F, COMENTARIOS, REALIZO) VALUES ('$ORDEN_SERVICIO', '$REQUISICION_POR','$OTRO_REQUISICION_POR','$EDO_REQUISICION','$FECHA_SOLICITUD_ALMACEN', '$FECHA_SUMINISTRO', '$NUM_F', '$COMENTARIOS', '$REALIZO')";



$row_insert=setArraySQL($sql_insert);

 echo json_encode($row_insert);


?>