<?php
include_once('connection/conJSON.php');

$PROVEEDOR=$_POST['PROVEEDOR'];
$DIRECCION=$_POST['DIRECCION'];
$CONTACTO1=$_POST['CONTACTO1'];
$TELEFONO1=$_POST['TELEFONO1'];
$EMAIL1=$_POST['EMAIL1'];

$CONTACTO2=$_POST['CONTACTO2'];
$TELEFONO2=$_POST['TELEFONO2'];
$EMAIL2=$_POST['EMAIL2'];

$CONTACTO3=$_POST['CONTACTO3'];
$TELEFONO3=$_POST['TELEFONO3'];
$EMAIL3=$_POST['EMAIL3'];

$MARCAS=$_POST['MARCAS'];
$EQUIPOS=$_POST['EQUIPOS'];
$ESTADO='ACTIVO';
$ESTADO_REPUBLICA=$_POST['ESTADO_REPUBLICA'];

$sql_insert="INSERT INTO proveedores(PROVEEDOR, DIRECCION, CONTACTO1, TELEFONO1, EMAIL1, CONTACTO2, TELEFONO2, EMAIL2, CONTACTO3, TELEFONO3, EMAIL3, MARCAS, EQUIPOS, ESTADO, ESTADO_REPUBLICA) VALUES ('$PROVEEDOR','$DIRECCION', '$CONTACTO1', '$TELEFONO1', '$EMAIL1', '$CONTACTO2', '$TELEFONO2', '$EMAIL2', '$CONTACTO3', '$TELEFONO3', '$EMAIL3', '$MARCAS', '$EQUIPOS', '$ESTADO', '$ESTADO_REPUBLICA')";

 //echo json_encode($sql_insert);
 
$row_insert=setArraySQL($sql_insert);

 echo json_encode($row_insert);


?>